### ISSUE TITLE
Tip to build a gaussian kernel matrix

### ISSUE THREAD

**Issue by SamGG** [LuisLauM/imagine#5]
Hi,
Thanks for providing a fast way for image processing.
Could you point me to a resource to build a gaussian kernel? Maybe I missed this in the doc.
Best,
Samuel

**Comment by LuisLauM** [comment]
Hi.

If you are looking to build a Gaussian kernel (a matrix), you could use what is suggested in [this Stackoverflow question](https://stackoverflow.com/questions/22747916/how-to-generate-a-discrete-2d-gaussian-smoothing-kernel-using-r).

```
# 9x9 (matrix) kernel
gaussKnl <- dnorm(x = seq(from = -2.5, to = 2.5, length.out = 9))
gaussKnl <- gaussKnl/max(gaussKnl)
gaussKnl <- gaussKnl %*% t(gaussKnl)

image(gaussKnl, asp = 1)
```

![image](https://github.com/user-attachments/assets/177ace8f-56db-490a-b3a1-94324e57c7c4)

Regards.

**Comment by SamGG** [comment]
Thanks. Maybe this should be added to the doc.
